name: 02 - Workflow Events
on:
    #push:
    workflow_dispatch:
    #pull_request:
    #    types: [opened, synchronize]

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run : |
                echo "Starting step show the trigger"
                echo "Event that triggered the workflow : ${{ github.event_name }}"