name: 03 - Workflow Runners
on: 
    workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: ubuntu echo
              run : |
                echo "This job is running on Ubuntu runner."
                echo "This job is running on : ${RUNNER_OS}"

            - name: windows echo
              shell: bash
              run: |
                echo "This job is running on Windows runner."
                echo "OS : ${RUNNER_OS}"
