name: 03 - Workflow Runners
on: 
    workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: ubuntu echo
              run : |
                echo "This job is running on Ubuntu runner."
                echo "This job is running on : ${RUNNER_OS}"

    windows-echo:
        runs-on: windows-latest
        steps:
            - name: windows echo
              shell: bash
              run: |
                echo "This Job is running on Windows"
                echo " OS : ${RUNNER_OS}"        