name: 05 - 02 - Event filters and Activity types
on:
    workflow_dispatch:
    # pull_request:
    #     types: [closed]
    #     branches: main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo PR status
              run: |
               echo "PR is closed - "
               echo "Ref branch : ${{ github.base_ref }}"
               echo "Head branch : ${{ github.head_ref }}" 
